//
// Created by danie on 4/11/2021.
//

#ifndef PHONEBOOK_PHONEBOOK_H
#define PHONEBOOK_PHONEBOOK_H


class phonebook {


    //TODO Show Contact INFO
    //TODO ADD CONTACT MANUALLY
    //TODO EDIT EXISTING CONTACT
    //TODO DELETE INDIVIDUAL CONTACT
    //TODO DELETE ALL CONTACT

    //TODO VALIDATIONS

    //TODO LOAD CONTACTS FROM FILE or API
    //TODO SAVE CONTACT TO FILE


    //TODO SEARCH CONTACT

    //TODO HEAP IMPLEMENTATION
    //TODO VECTOR WITH BINARY SEARCH IMPLEMENTATION
    //TODO BST IMPLEMENTATION
    //TODO TRIE IMPLEMENTATION???

};


#endif //PHONEBOOK_PHONEBOOK_H
